# configtx.yaml from aws managedblockchain
# https://docs.aws.amazon.com/managed-blockchain/latest/managementguide/managed-blockchain-mgmt.pdf

# need to modify the org's Name and ID

Organizations:
    - &org1
        Name: <member ID>
        ID: <member ID>
        MSPDir: /opt/home/org1-msp
        AnchorPeers:
            - Host:
              Port: 

Application: &ApplicationDefaults
     Organizations:

Profiles:
    OneOrgChannel:
        Consortium: AWSSystemConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *org1
